### ISSUE TITLE
Missing dependency on requirements

### ISSUE THREAD

**Issue by soynerdito** [commonwealth-of-puerto-rico/libre#4] opened 2013-08-25 20:23 UTC
Missing requirement: 
django-jsonfield==0.9.10

When running "./manage.py syncdb --migrate" showed error "ValueError: Cannot import the required field 'jsonfield.fields.JSONField"
appears to be a missing dependency on the requirements for the library django-jsonfield.
I ran:
pip install django-jsonfield
and it works

The shell looked similar to this.
![libre_migrate_error](https://f.cloud.github.com/assets/1137166/1023003/ecc806f2-0dc3-11e3-80fd-53500c2150e9.png)

**Comment by ghost** [comment] 2013-08-25 22:08
Problem was caused by references to a field type no longer used in the current version. Fixed by replacing all instances of **jsonfield.fields.JSONField** with **django.db.models.fields.TextField** (which is what **JSONField** subclasses in the first place). Thanks for testing and reporting!

**Closed as completed by ghost** 2013-08-25 22:08 UTC
